name: Build Extension

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main]

jobs:
    test-build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Validate manifest.json
              run: |
                  echo "Validating manifest.json..."
                  if ! jq empty manifest.json; then
                    echo "❌ manifest.json is not valid JSON"
                    exit 1
                  fi
                  echo "✅ manifest.json is valid"

            - name: Check required files
              run: |
                  echo "Checking required extension files..."
                  required_files=(
                    "manifest.json"
                    "background.js"
                    "content_script.js"
                    "options.html"
                    "options.js"
                    "popup.html"
                    "popup.js"
                    "icons/icon16.png"
                    "icons/icon48.png"
                    "icons/icon128.png"
                  )

                  for file in "${required_files[@]}"; do
                    if [ -f "$file" ]; then
                      echo "✅ $file exists"
                    else
                      echo "❌ $file is missing"
                      exit 1
                    fi
                  done

            - name: Get version from manifest
              id: get_version
              run: |
                  VERSION=$(cat manifest.json | grep '"version"' | sed 's/.*"version": "\(.*\)".*/\1/')
                  echo "version=$VERSION" >> $GITHUB_OUTPUT
                  echo "Version found: $VERSION"

            - name: Test build extension
              run: |
                  # Create test build directory
                  mkdir -p test-build

                  # Copy all necessary files
                  cp manifest.json test-build/
                  cp background.js test-build/
                  cp content_script.js test-build/
                  cp options.html test-build/
                  cp options.js test-build/
                  cp popup.html test-build/
                  cp popup.js test-build/
                  cp -r icons test-build/

                  # Verify all files are in place
                  echo "Files in test-build:"
                  find test-build -type f | sort

                  # Create test zip
                  cd test-build
                  zip -r ../CleanURLs-test-build.zip .
                  cd ..

                  echo "✅ Extension built successfully"

            - name: Upload test build
              uses: actions/upload-artifact@v4
              with:
                  name: test-build-${{ github.sha }}
                  path: CleanURLs-test-build.zip
                  retention-days: 7
